[package]
name = "sfdisk_sort_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.59"
lazy_static = "1.4.0"
regex = "1.6.0"
